### ISSUE TITLE
Tag broken builds

### ISSUE THREAD

**Issue by SylvainCorlay** [conda-forge/pybind11_json-feedstock#3]
The following build artefacts are broken (they should have a pythonX.X flavor)

`pybind11_json-0.2.2-hdc96acc_0.tar.bz2`
`pybind11_json-0.2.2-he980bc4_0.tar.bz2`
`pybind11_json-0.2.2-ha1b3eb9_0.tar.bz2`
`pybind11_json-0.2.2-hc9558a2_0.tar.bz2`

Would it be possible to tag them as  "broken" on Anaconda.org?

cc @conda-forge/core

**Comment by ocefpaf** [comment]
Done. Can you check: https://anaconda.org/conda-forge/pybind11_json/files?version=0.2.2 ?

**Comment by SylvainCorlay** [comment]
Yeah! Thanks @ocefpaf !
